apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment
  labels: 
    app: nginx
spec: #deployment spec
  replicas: 1
  selector: 
    matchLabels: 
      app: nginx
  template: 
    metadata: 
      labels: 
        app: nginx
    spec: #pod spec
      containers: 
      - name: nginx
      image: nginx:1.16
      ports: 
        containerPort: 80